version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/dojopop-xyz"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Z0rlord"
    assignees:
      - "Z0rlord"
    commit-message:
      prefix: "security"
      include: "scope"
    # Group all patch updates together
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "all"
    # Ignore specific packages if needed (uncomment and modify as needed)
    # ignore:
    #   - dependency-name: "package-name"
    #     versions: ["1.x", "2.x"]
